[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#1f77b4"
backgroundColor = "#000000"
secondaryBackgroundColor = "#020530"
textColor = "#ffffff"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = true
