"""create account table

Revision ID: c33d5d08e981
Revises: 
Create Date: 2024-11-04 21:19:27.360499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c33d5d08e981'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('algorithm_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('algorithm_id'),
    schema='service_algorithm_analysis'
    )
    op.create_table('criteria',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('criteria_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('criteria_id'),
    schema='service_algorithm_analysis'
    )
    op.create_table('algorithm_criteria',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('algorithm_criteria_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('algorithm_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criteria_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['service_algorithm_analysis.algorithm.algorithm_id'], ),
    sa.ForeignKeyConstraint(['criteria_id'], ['service_algorithm_analysis.criteria.criteria_id'], ),
    sa.PrimaryKeyConstraint('algorithm_criteria_id'),
    schema='service_algorithm_analysis'
    )
    op.create_index('idx_algorithm_criteria_algorithm', 'algorithm_criteria', ['algorithm_id'], unique=False, schema='service_algorithm_analysis')
    op.create_index('idx_criteria_algorithm_criteria', 'algorithm_criteria', ['criteria_id'], unique=False, schema='service_algorithm_analysis')
    op.create_table('input',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('input_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('algorithm_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('input_type', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['service_algorithm_analysis.algorithm.algorithm_id'], ),
    sa.PrimaryKeyConstraint('input_id'),
    schema='service_algorithm_analysis'
    )
    op.create_index('idx_input_algorithm', 'input', ['algorithm_id'], unique=False, schema='service_algorithm_analysis')
    op.create_table('report',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('report_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('algorithm_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report_alias', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['service_algorithm_analysis.algorithm.algorithm_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    schema='service_algorithm_analysis'
    )
    op.create_index('idx_report_algorithm', 'report', ['algorithm_id'], unique=False, schema='service_algorithm_analysis')
    op.create_table('payload',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('payload_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('report_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('input_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('input_value', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['input_id'], ['service_algorithm_analysis.input.input_id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['service_algorithm_analysis.report.report_id'], ),
    sa.PrimaryKeyConstraint('payload_id'),
    schema='service_algorithm_analysis'
    )
    op.create_index('idx_payload_input', 'payload', ['input_id'], unique=False, schema='service_algorithm_analysis')
    op.create_index('idx_payload_report', 'payload', ['report_id'], unique=False, schema='service_algorithm_analysis')
    op.create_table('result',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('result_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('report_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criteria_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['criteria_id'], ['service_algorithm_analysis.criteria.criteria_id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['service_algorithm_analysis.report.report_id'], ),
    sa.PrimaryKeyConstraint('result_id'),
    schema='service_algorithm_analysis'
    )    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###    
    op.drop_index('idx_result_report', table_name='result', schema='service_algorithm_analysis')
    op.drop_index('idx_result_criteria', table_name='result', schema='service_algorithm_analysis')
    op.drop_table('result', schema='service_algorithm_analysis')
    op.drop_index('idx_payload_report', table_name='payload', schema='service_algorithm_analysis')
    op.drop_index('idx_payload_input', table_name='payload', schema='service_algorithm_analysis')
    op.drop_table('payload', schema='service_algorithm_analysis')
    op.drop_index('idx_report_algorithm', table_name='report', schema='service_algorithm_analysis')
    op.drop_table('report', schema='service_algorithm_analysis')
    op.drop_index('idx_input_algorithm', table_name='input', schema='service_algorithm_analysis')
    op.drop_table('input', schema='service_algorithm_analysis')
    op.drop_index('idx_criteria_algorithm_criteria', table_name='algorithm_criteria', schema='service_algorithm_analysis')
    op.drop_index('idx_algorithm_criteria_algorithm', table_name='algorithm_criteria', schema='service_algorithm_analysis')
    op.drop_table('algorithm_criteria', schema='service_algorithm_analysis')
    op.drop_table('criteria', schema='service_algorithm_analysis')
    op.drop_table('algorithm', schema='service_algorithm_analysis')
    # ### end Alembic commands ###
